<?php
echo "DIBILANGIN DAH MAMPUS GA BISA DIPAKE NGEYEL, MAU YG BARU? PM OWNER YG PUNYA NYA YA JGN MAKE GRATISAN, HATI HATI PENIPUAN, ADMIN ASLI PEMILIK SCRIPT INI HANYA @LC_DEV dan CHANNEL NYA @Lc_ScWingoReal";
goto close;

close:
